-- TODO: fork every depencencies and use it
-- TODO: add project folder to telescope repo
-- TODO: replace sidebar todo grepper with better one
-- TODO: fix sidebar file explorer root finder
-- TODO: show messages with floating window for each print call, and with location of print this message
-- TODO: fix find file sorting to last closed file
-- TODO: refactoring with feature first architecture, for example:
-------------------------------
-- init.lua                  --
-- core                      --
--    init.lua               --
--    utils.lua              --
--    keymaps.lua            --
--    options.lua            --
-- plugins                   --
--    init.lua               --
--    telescope              --
--        init.lua           --
--        keymaps.lua        --
--        options.lua        --
--        highlights.lua     --
-------------------------------
-- TODO: better cmdline, remap ':' to open floating window
-- scratch buffer with vim and lua syntax highlighting,
-- with history of commands, and with ability to execute command
-- feature's
-- TODO: when print, open floating window with highligting.
-- TODO: send selection to floating cmdline.
-- if selection is nvim command, translate it excutable in cmdline.
-- TODO: Add yaml support for config
-- TODO: Replace lua with luau
