return function()
  local colors = require("poimandres.palette")

  local NavicColors = {
    NavicIconsModule = { default = true, fg = colors.blue1 },
    NavicIconsNamespace = { default = true, fg = colors.blue1 },
    NavicIconsPackage = { default = true, fg = colors.blue1 },
    NavicIconsClass = { default = true, fg = colors.blue1 },
    NavicIconsMethod = { default = true, fg = colors.blue1 },
    NavicIconsProperty = { default = true, fg = colors.blue1 },
    NavicIconsField = { default = true, fg = colors.blue1 },
    NavicIconsConstructor = { default = true, fg = colors.blue1 },
    NavicIconsEnum = { default = true, fg = colors.blue1 },
    NavicIconsInterface = { default = true, fg = colors.blue1 },
    NavicIconsFunction = { default = true, fg = colors.blue1 },
    NavicIconsVariable = { default = true, fg = colors.blue1 },
    NavicIconsConstant = { default = true, fg = colors.blue1 },
    NavicIconsString = { default = true, fg = colors.blue1 },
    NavicIconsNumber = { default = true, fg = colors.blue1 },
    NavicIconsBoolean = { default = true, fg = colors.blue1 },
    NavicIconsArray = { default = true, fg = colors.blue1 },
    NavicIconsObject = { default = true, fg = colors.blue1 },
    NavicIconsKey = { default = true, fg = colors.blue1 },
    NavicIconsNull = { default = true, fg = colors.blue1 },
    NavicIconsEnumMember = { default = true, fg = colors.blue1 },
    NavicIconsStruct = { default = true, fg = colors.blue1 },
    NavicIconsEvent = { default = true, fg = colors.blue1 },
    NavicIconsOperator = { default = true, fg = colors.blue1 },
    NavicIconsTypeParameter = { default = true, fg = colors.blue1 },
    NavicIconsFile = { default = true, fg = colors.blue1 },
    NavicText = { default = true, fg = colors.text },
  }

  for hl, col in pairs(NavicColors) do
    vim.api.nvim_set_hl(0, hl, col)
  end
  require("nvim-navic").setup({
    icons = {
      File = " ",
      Module = " ",
      Namespace = " ",
      Package = " ",
      Class = " ",
      Method = " ",
      Property = " ",
      Field = " ",
      Constructor = " ",
      Enum = "練",
      Interface = "練",
      Function = " ",
      Variable = " ",
      Constant = " ",
      String = " ",
      Number = " ",
      Boolean = "◩ ",
      Array = " ",
      Object = " ",
      Key = " ",
      Null = "ﳠ ",
      EnumMember = " ",
      Struct = " ",
      Event = " ",
      Operator = " ",
      TypeParameter = " ",
    },
    highlight = true,
    separator = " > ",
    depth_limit = 0,
    depth_limit_indicator = "..",
    safe_output = true,
  })
end
